config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  # devise_for :users, controllers: { registrations: 'users/registrations'}
  devise_for :users

  resource :dashboard, only: :show, controller: 'dashboard'
  resources :groups, only: [:create, :show]
  resource :locale, only: :update
  resources :personal_balances, only: [:create, :show]
  resources :personal_records, only: [:create, :update, :destroy]
  resources :records, only: [:create, :update, :destroy]

  root 'dashboard#show'

end

app/views/layouts/_flashes.html.slim
- flash.each do |key, value|
  - if key != 'html_safe'
    = content_tag :div, class: "alert #{bootstrap_class_for(key)} fade in", role: "alert"
      button type="button" class="close" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span class="sr-only"
          | Close
      = flash[:html_safe] ? raw(value) : value

app/views/layouts/_header.html.slim
.navbar
  = link_to root_path, class: 'logo' do
    span
      = image_tag('tirelire_no_background.png', alt: 'Accounts', height: 50)
      | Accounts

  .profile-container.pull-right
    - if user_signed_in?
      ul.list-inline
        li = image_tag current_user.gravatar_url(size: 50)
        li = t('header.welcome', name: current_user.email)
        - unused_locales.each do |locale|
          li = link_to locale.to_s.capitalize, locale_path(locale: locale), method: :put
        li = link_to t('header.sign_out'), destroy_user_session_path, method: :delete
    - else
      .sign_up_link
        ul.list-inline
          - unused_locales.each do |locale|
            li = link_to locale.to_s.capitalize, locale_path(locale: locale), method: :put
          li = link_to t('devise.shared.links.sign_up'), new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Accounts
    = favicon_link_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .wrapper
      = render 'layouts/header'
      .container.main-container
        = render 'layouts/flashes'
        = yield

javascript:
  I18n.defaultLocale = "#{{I18n.default_locale.to_s}}";
  I18n.locale = "#{{I18n.locale.to_s}}";
  $.fn.datepicker.defaults.language = "#{{(I18n.locale || I18n.default_locale).to_s}}";